### ISSUE TITLE
Modificar hola mundo 

### ISSUE THREAD

**Issue by davleorui** [davleorui/PGPILAB8#7]
Añadir un contador que vaya mostrando "Hola Mundo 1" "Hola Mundo 2" "Hola Mundo 3" .... @Marta010  o @yeyodebote

**Comment by Marta010** [comment]
@davleorui @yeyodebote me pongo a ello

**Comment by yeyodebote** [comment]
@davleorui  @Marta010 yo  he hecho una modificación
